### ISSUE TITLE
no title tiles...

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#117]
Hi

some versions ago when a text tile had no title and text it was simplay blank. for some versions now it shows (no title) instead.
This is annoying as I used blanks to design my UI.
Can we get the old behaviour back or get a blank tile instead?

**Comment by igorgladkov** [comment]
@fsedarkalex that was actually a bug fix since it is not intended behavior to leave out for some widgets. While I could introduce blank tile it would be a workaround that would need to be removed later on, since I have a better final solution in mind, but it requires more time implement.
Let me think about this.

**Comment by fsedarkalex** [comment]
I can live with that for now... So if you have a better plan focus on this.

**Comment by fsedarkalex** [comment]
Igor I found a workaround... Text label="   " :) Is that okay for you? :)

**Comment by fsedarkalex** [comment]
But even better is of course a solution where no tile is displayed at all for layouting. Looking forward to see your solution :)

**Comment by arraylabs** [comment]
Could you simply create a transparent .png image and use an image widget?

**Comment by johnjore** [comment]
I too use this to create empty / blank cell's. (text iitem=" ")

**Comment by therealtobo** [comment]
Having a blank widget would be really nice, meaning that it doesn't display anything, not even a box, but rather just takes up the space.
