### ISSUE TITLE
Android version 4.3 

### ISSUE THREAD

**Issue by mlava** [igorgladkov/rotini#156]
Hi Igor,
Any idea if you will eventually support 4.3?
I have a tablet just sitting there waiting... :-)
Cheers

**Comment by igorgladkov** [comment]
That would depend on two things: how much interest from the user base in that version and how much time investment it will need.
To be honest though, 4.3 now has just a few percent of usage for all Androids, so that wouldn't be a priority to investigate amount of time investment needed at this point.

**Comment by igorgladkov** [comment]
At this point, no 4.3 support is planned for the new beta. given the relatively low usage of that Android version.
