### ISSUE TITLE
Window State "Tilted"

### ISSUE THREAD

**Issue by michaeljoos72** [igorgladkov/rotini#159]
Hi Igor

Just bought a new homematic window-sensor that supports 3 states: open, closed, tilted
Can you please add also "tilted" to widget window-sensor?

Thanks
Michael

**Comment by igorgladkov** [comment]
Added in 0.20 release

**Comment by M-ax-G** [comment]
OH has a state for tilted called ajar. Does the window-sensor require ajar or tilted in order to work?

**Comment by igorgladkov** [comment]
@M-ax-G What binding and item has ajar state?

**Comment by M-ax-G** [comment]
Hi Igor,

It is a standard /default behaviour for a contact, which can also be a 
switch... (in 1.8.3, which I am using).. and has also the -ajar icons.

Here some .items
String  Window_House_Kitchen            "Kitchen Window 
[MAP(en.map):%s]"    <contact>    (gHouse_Kitchen, gHouse_Windows, 
gHouse_Veranda) 
{mqtt="<[mymosquitto:ArgyleCourt/House/Kitchen/Window:state:default]"}
String  Window_House_Living            "Living Window 
[MAP(en.map):%s]"    <contact>    (gHouse_Living, gHouse_Windows) 
{mqtt="<[mymosquitto:ArgyleCourt/House/Living/Window:state:default]"}

Group:String:AND("CLOSED", "OPEN")    gHouse_Windows    "Open Windows 
[(%d)]"    <contact>

Congratulations to a very nice piece of work -- I love it. Clean. It is 
a driver to continue with OH. In fact, since this app is available on 
Android, I will be getting Raspberries v3 with a touch panel running 
Android for room controls.
Keep up the great work!

Best regards,
Max

Igor Gladkov wrote on 23/08/2016 00:48:
