### ISSUE TITLE
Text widget don't display icon

### ISSUE THREAD

**Issue by tiny-tinker** [igorgladkov/rotini#162]
Hi all,
   I have these two widgets:

```
    Frame label="Sunrise {widget:text}" {
        Text item=Sunrise_Time
    }

    Frame label="Sunset {widget:text}" {
        Text item=Sunset_Time label="{icon:bed}"
    }
```

Where:

```
DateTime    Sunrise_Time    "Sunrise [%1$tH:%1$tM]" { astro="planet=sun, type=rise, property=start" }
DateTime    Sunset_Time "Sunset [%1$tH:%1$tM]" { astro="planet=sun, type=set, property=end" }

```

But the icon doesn't show on the sunset and instead, the full YYY-MM-DDThh:mm:ss date is displayed in the sunset widget. Am I doing something wrong with the item or the widget? Any ideas?

**Comment by igorgladkov** [comment]
Text widget is just that - text, so no icon support. The widget is not intended to be used as final solution and exists mainly because there are some gaps in functionality and for testing to get raw item value.
In your particular case, there will be a dedicated sunrise-sunset widget released in the future.

**Comment by tiny-tinker** [comment]
Great! Thanks!
