### ISSUE TITLE
Group Gauges displays wrong icons

### ISSUE THREAD

**Issue by frode** [igorgladkov/rotini#96]
I have set up a group gauge with 4 gauges.

  Frame label="Raspberry Pi / openHAB {widget:gauge-group}" {
    Text item=memUsed label="{unit:MB,max:1024}" icon="database"
    Text item=cpuCombined label="{unit:%}" icon="memory"
    Text item=Raspi_temp label="{unit:deg,max:180}" icon="memory"
    Text item=openhabRealMem label="{unit:MB,max:1024}" icon="database"
  }

All these display as a general gauge icon, the one named "gauge" ..

When i changed one of them to use icon="hdd" it changed to hdd icon for that one only, all 3 others remain on the gauge icon.

**Comment by igorgladkov** [comment]
@frode Because of some processing OpenHAB is doing on "icon" values which does different things based on item value and such, I would recommend using Rotini icon config instead:

```
Text item=memUsed label="{unit:MB,max:1024,icon:database}"
```

Will update wiki as well.

Btw, there are quite a few fixes for Gauge Group widget in 0.5.41, so if you have any other issues those might be fixed after release.
